version: 2.1
jobs:
  print_name:
    docker:
      - image: cimg/base:stable
    environment:
      MY_NAME: Dan
    steps:
      - checkout
      - run:
          command: echo ${MY_NAME}
workflows:
  print-name-workflow:
    jobs:
      - print_name
