version: 2.1
jobs:
  print_name:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "echo an env var that prints my name"
          command: echo ${MY_NAME}
workflows:
  print-name-workflow:
    jobs:
      - print_name
